language: php
php:
    - 5.5

before_script:
    - composer selfupdate
    - composer install --prefer-source

script:
    - mkdir -p build/logs
    - phpunit -c phpunit.xml.dist

after_script:
    - travis_retry php vendor/bin/coveralls -v